# Generated by Django 6.0.3 on 2026-03-30 19:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_prep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studycalendar',
            name='tasks_completed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studycalendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_calendar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='order_index',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='todo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='interview_prep.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='interview_prep.role'),
        ),
        migrations.AlterField(
            model_name='usertodoprogress',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='interview_prep.todo'),
        ),
        migrations.AlterField(
            model_name='usertodoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studycalendar',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_entry'),
        ),
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(fields=('topic', 'title'), name='unique_todo_per_topic'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('role', 'name'), name='unique_topic_per_role'),
        ),
        migrations.AddConstraint(
            model_name='usertodoprogress',
            constraint=models.UniqueConstraint(fields=('user', 'todo'), name='unique_user_todo_progress'),
        ),
    ]
