# Generated by Django 6.0.1 on 2026-01-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
