# Generated by Django 6.0.2 on 2026-02-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
    ]
