# Generated by Django 6.0.2 on 2026-02-22 20:28

import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default='resumes/default.pdf', upload_to=resumes.models.get_file_path),
            preserve_default=False,
        ),
    ]
